ParameterDefinitions = {
    {g5, { Description -> "SU(5) gauge coupling",
           Real -> True,
           LesHouches -> {GAUGE, 4},
           LaTeX -> "g_5",
           OutputName -> g5
         } },
    {gX,   { Description -> "U(1)_X gauge coupling",
             Real -> True,
             LesHouches -> {GAUGE, 6},
             LaTeX -> "g_X",
             OutputName -> gX
           } },
    {lam1, { Description -> "(10-10)-(10-10) quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 1},
             LaTeX -> "\\lambda_1",
             OutputName -> lam1
           } },
    {lam2, { Description -> "(10-10-10-10) quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 2},
             LaTeX -> "\\lambda_2",
             OutputName -> lam2
           } },
    {lam3, { Description -> "(5-5-5-5) quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 3},
             LaTeX -> "\\lambda_3",
             OutputName -> lam3
           } },
    {lam3t, { Description -> "(5'-5'-5'-5') quartic coupling",
              Real -> True,
              LesHouches -> {SU5MIX, 4},
              LaTeX -> "\\tilde{\\lambda}_3",
              OutputName -> lam3t
           } },
    {lam4, { Description -> "(10-10)-(5-5) quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 5},
             LaTeX -> "\\lambda_4",
             OutputName -> lam4
           } },
    {lam4t, { Description -> "(10-10)-(5'-5') quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 6},
             LaTeX -> "\\tilde{\\lambda}_4",
             OutputName -> lam4t
           } },
    {lam5, { Description -> "(5-10-10-5) quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 7},
             LaTeX -> "\\lambda_5",
             OutputName -> lam5
           } },
    {lam5t, { Description -> "(5'-10-10-5') quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 8},
             LaTeX -> "\\tilde{\\lambda}_5",
             OutputName -> lam5t
           } },
    {lam6, { Description -> "(5-5')-(5'-5) quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 9},
             LaTeX -> "\\lambda_6",
             OutputName -> lam6
           } },
    {lam6t, { Description -> "(5-5)-(5'-5') quartic coupling",
             Real -> True,
             LesHouches -> {SU5MIX, 10},
             LaTeX -> "\\tilde{\\lambda}_6",
             OutputName -> lam6t
           } },
    {lam7,  { Description -> "(5-5')-(10-10) quartic coupling",
             Real -> False,
             LesHouches -> {SU5MIX, 11},
             LaTeX -> "\\lambda_7",
             OutputName -> lam7
           } },
    {lam8,  { Description -> "(5-10-10-5') quartic coupling",
             Real -> False,
             LesHouches -> {SU5MIX, 12},
             LaTeX -> "\\lambda_8",
             OutputName -> lam8
           } },
    {eta1,  { Description -> "(5-5)-(5-5') quartic coupling",
             Real -> False,
             LesHouches -> {SU5MIX, 13},
             LaTeX -> "\\eta_1",
             OutputName -> eta1
           } },
    {eta2,  { Description -> "(5-5')-(5-5') quartic coupling",
             Real -> False,
             LesHouches -> {SU5MIX, 14},
             LaTeX -> "\\eta_2",
             OutputName -> eta2
           } },
    {eta3,  { Description -> "(5-5')-(5'-5') quartic coupling",
             Real -> False,
             LesHouches -> {SU5MIX, 15},
             LaTeX -> "\\eta_3",
             OutputName -> eta3
           } },
    {m10sq,  { Description -> "Scalar 10 squared mass",
             Real -> True,
             LesHouches -> {SU5MIX, 16},
             LaTeX -> "m_{10}^2",
             OutputName -> m10sq
           } },
    {m5sq,  { Description -> "Scalar 5 squared mass",
             Real -> True,
             LesHouches -> {SU5MIX, 17},
             LaTeX -> "m_{5}^2",
             OutputName -> m5sq
           } },
    {m5psq,  { Description -> "Scalar 5' squared mass",
             Real -> True,
             LesHouches -> {SU5MIX, 18},
             LaTeX -> "m_{5^\\prime}^2",
             OutputName -> m5psq
           } },
    {m12sq,  { Description -> "Scalar 5-5' mixing",
             Real -> False,
             LesHouches -> {SU5MIX, 19},
             LaTeX -> "m_{12}^2",
             OutputName -> m12sq
           } },
    {mu5,  { Description -> "Scalar 10-10-5 mixing",
             Real -> False,
             LesHouches -> {SU5MIX, 20},
             LaTeX -> "\\mu",
             OutputName -> mu5
           } },
    {mu5p,  { Description -> "Scalar 10-10-5' mixing",
             Real -> False,
             LesHouches -> {SU5MIX, 21},
             LaTeX -> "\\mu'",
             OutputName -> mu5p
           } },
    {QXPhi10, { Description -> "10-plet scalar U(1)_X charge",
                Real -> True,
                LesHouches -> {U1XCHARGE, 1},
                LaTeX -> "Q^X_{10_S}",
                OutputName -> QXPhi10
              } },
    {QXPhi5, { Description -> "5-plet scalar U(1)_X charge",
                Real -> True,
                LesHouches -> {U1XCHARGE, 2},
                LaTeX -> "Q^X_{5_S}",
                OutputName -> QXPhi5
              } },
    {QXPhi5, { Description -> "5'-plet scalar U(1)_X charge",
                Real -> True,
                LesHouches -> {U1XCHARGE, 3},
                LaTeX -> "Q^X_{5_S^\\prime}",
                OutputName -> QXPhi5p
              } }
};
